#!/usr/bin/env python3
"""
Remote install: YAML config -> .env on server -> ./deploy.sh over SSH.
"""
from __future__ import annotations

import argparse
import fnmatch
import io
import os
import re
import shlex
import sys
import tarfile
from pathlib import Path
from typing import Any

import paramiko
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
REMOTE_DEPLOY_DIR = Path(__file__).resolve().parent
ENV_EXAMPLE = REPO_ROOT / ".env.example"

ENV_SUBST_PATTERN = re.compile(r"\$\{ENV:([^}]+)\}")

# Paths excluded when packing local source (relative to repo root)
TAR_EXCLUDE_NAMES = {
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    "node_modules",
    ".cursor",
}
TAR_EXCLUDE_GLOBS = ("*.pyc", "*.pyo", ".env")


def expand_env_vars(obj: Any, environ: dict[str, str] | None = None) -> Any:
    environ = environ or os.environ

    def subst(s: str) -> str:
        def repl(m: re.Match[str]) -> str:
            key = m.group(1).strip()
            if key not in environ:
                raise KeyError(f"Environment variable {key!r} required by config (${{ENV:{key}}})")
            return environ[key]

        return ENV_SUBST_PATTERN.sub(repl, s)

    if isinstance(obj, str):
        return subst(obj)
    if isinstance(obj, dict):
        return {k: expand_env_vars(v, environ) for k, v in obj.items()}
    if isinstance(obj, list):
        return [expand_env_vars(x, environ) for x in obj]
    return obj


def parse_env_example(path: Path) -> tuple[list[str], dict[str, str]]:
    order: list[str] = []
    defaults: dict[str, str] = {}
    text = path.read_text(encoding="utf-8")
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "=" in stripped:
            key, _, val = stripped.partition("=")
            key = key.strip()
            order.append(key)
            defaults[key] = val.rstrip("\r")
    return order, defaults


def merge_env(order: list[str], defaults: dict[str, str], overrides: dict[str, Any]) -> dict[str, str]:
    merged = dict(defaults)
    for k, v in overrides.items():
        if v is None:
            continue
        key = str(k).strip().upper()
        merged[key] = str(v).strip() if isinstance(v, (str, int, float)) else str(v)
    return merged


def render_env_file(order: list[str], merged: dict[str, str]) -> str:
    lines: list[str] = [
        "# Generated by remote-deploy/install.py. Do not edit on server; re-run install from your machine.",
        "",
    ]
    seen = set()
    for key in order:
        if key in merged:
            lines.append(f"{key}={merged[key]}")
            seen.add(key)
    for key in sorted(merged.keys()):
        if key not in seen:
            lines.append(f"{key}={merged[key]}")
    lines.append("")
    return "\n".join(lines)


def should_exclude_tar(path: Path, repo_root: Path) -> bool:
    try:
        rel = path.relative_to(repo_root)
    except ValueError:
        return True
    parts = rel.parts
    if parts and parts[0] == "remote-deploy":
        return True
    for p in parts:
        if p in TAR_EXCLUDE_NAMES:
            return True
    name = path.name
    for g in TAR_EXCLUDE_GLOBS:
        if fnmatch.fnmatch(name, g):
            return True
    return False


def pack_local_repo(repo_root: Path) -> bytes:
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for root, dirs, files in os.walk(repo_root, topdown=True):
            root_path = Path(root)
            dirs[:] = [
                d
                for d in dirs
                if d not in TAR_EXCLUDE_NAMES
                and not should_exclude_tar(root_path / d, repo_root)
            ]
            for name in files:
                p = root_path / name
                if should_exclude_tar(p, repo_root):
                    continue
                arc = p.relative_to(repo_root)
                tar.add(p, arcname=str(arc).replace("\\", "/"))
    return buf.getvalue()


def load_private_key(path: Path) -> paramiko.PKey:
    path = path.expanduser()
    if not path.is_file():
        raise FileNotFoundError(f"SSH key not found: {path}")
    last_err: Exception | None = None
    for cls in (
        paramiko.Ed25519Key,
        paramiko.ECDSAKey,
        paramiko.RSAKey,
    ):
        try:
            return cls.from_private_key_file(str(path))
        except Exception as e:
            last_err = e
            continue
    raise RuntimeError(f"Cannot load private key {path}: {last_err}")


def connect_ssh(cfg: dict[str, Any]) -> paramiko.SSHClient:
    ssh_cfg = cfg["ssh"]
    host = ssh_cfg["host"]
    port = int(ssh_cfg.get("port", 22))
    user = ssh_cfg["user"]
    password = ssh_cfg.get("password")
    env_pw = ssh_cfg.get("ssh_password_env")
    if env_pw:
        password = os.environ.get(env_pw)
    ident = ssh_cfg.get("identity_file")

    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    kwargs: dict[str, Any] = {
        "hostname": host,
        "port": port,
        "username": user,
        "timeout": 30,
        "allow_agent": True,
        "look_for_keys": not ident and not password,
    }
    if ident:
        kwargs["pkey"] = load_private_key(Path(str(ident)))
    elif password:
        kwargs["password"] = password
    else:
        raise SystemExit("ssh: set identity_file, password, or ssh_password_env (with env var set)")

    client.connect(**kwargs)
    return client


def run_remote(
    client: paramiko.SSHClient,
    cmd: str,
    *,
    dry_run: bool,
) -> tuple[int, str, str]:
    if dry_run:
        print(f"[dry-run] exec: {cmd}")
        return 0, "", ""
    stdin, stdout, stderr = client.exec_command(cmd, get_pty=True)
    out = stdout.read().decode("utf-8", errors="replace")
    err = stderr.read().decode("utf-8", errors="replace")
    code = stdout.channel.recv_exit_status()
    return code, out, err


def upload_bytes(sftp: paramiko.SFTPClient, data: bytes, remote_path: str) -> None:
    with sftp.open(remote_path, "wb") as f:
        f.write(data)


def mask_env_for_print(text: str) -> str:
    out_lines = []
    for line in text.splitlines():
        if "=" not in line or line.strip().startswith("#"):
            out_lines.append(line)
            continue
        k, _, _ = line.partition("=")
        key = k.strip().upper()
        if any(x in key for x in ("PASSWORD", "SECRET", "TOKEN", "PRIVATE", "PRESHARED")):
            out_lines.append(f"{k.strip()}=(hidden)")
        else:
            out_lines.append(line)
    return "\n".join(out_lines) + ("\n" if text.endswith("\n") else "")


def main() -> None:
    ap = argparse.ArgumentParser(description="Deploy amnezia-wg-easy over SSH from YAML config.")
    ap.add_argument("--config", "-c", type=Path, default=REMOTE_DEPLOY_DIR / "config.yaml", help="Path to config YAML")
    ap.add_argument("--dry-run", action="store_true", help="Print actions and masked .env; no SSH.")
    args = ap.parse_args()

    if not args.config.is_file():
        print(f"Config not found: {args.config}", file=sys.stderr)
        print("Copy config.example.yaml to config.yaml and edit.", file=sys.stderr)
        sys.exit(1)

    raw = yaml.safe_load(args.config.read_text(encoding="utf-8")) or {}
    try:
        cfg = expand_env_vars(raw)
    except KeyError as e:
        print(f"Config env error: {e}", file=sys.stderr)
        sys.exit(1)

    if "ssh" not in cfg or "host" not in cfg["ssh"] or "user" not in cfg["ssh"]:
        sys.exit("Invalid config: ssh.host and ssh.user are required.")

    if not ENV_EXAMPLE.is_file():
        sys.exit(f".env.example not found at {ENV_EXAMPLE} (run from repo checkout).")

    order, defaults = parse_env_example(ENV_EXAMPLE)
    env_section = cfg.get("env") or {}
    if not isinstance(env_section, dict):
        sys.exit("Invalid config: env must be a mapping.")
    merged = merge_env(order, defaults, env_section)
    env_body = render_env_file(order, merged)

    remote_path = cfg.get("remote", {}).get("path", "/opt/amnezia-wg-easy")
    remote_path = remote_path.rstrip("/")

    print("--- Rendered .env (secrets masked in dry-run / log) ---")
    print(mask_env_for_print(env_body))

    source = cfg.get("source") or {}
    mode = (source.get("mode") or "git").lower()

    if args.dry_run:
        print("[dry-run] Would connect SSH and:")
        print(f"  1. Ensure Docker: docker compose version")
        print(f"  2. Sync source ({mode}) -> {remote_path}")
        print(f"  3. Upload .env -> {remote_path}/.env")
        print(
            f"  4. Stop stack (this project only, volumes kept): "
            f"cd {remote_path} && docker compose --profile letsencrypt down --remove-orphans"
        )
        print(f"  5. Run: cd {remote_path} && chmod +x deploy.sh && ./deploy.sh")
        return

    client = connect_ssh(cfg)
    try:
        code, out, err = run_remote(
            client,
            "docker compose version 2>/dev/null || docker compose version",
            dry_run=False,
        )
        if code != 0:
            print(err or out, file=sys.stderr)
            sys.exit(
                "Remote host: Docker Compose v2 is required (`docker compose version`). Install Docker Engine + Compose plugin."
            )

        if mode == "git":
            git_url = source.get("git_url")
            branch = source.get("branch", "master")
            if not git_url:
                sys.exit("source.git_url is required when source.mode is git")
            r = shlex.quote(remote_path)
            u = shlex.quote(str(git_url))
            b = shlex.quote(str(branch))
            script = f"""set -e
R={r}
URL={u}
BR={b}
if [ -f "$R/deploy.sh" ]; then
  cd "$R" && git fetch origin && git checkout "$BR" && git pull
elif [ -d "$R" ]; then
  echo "Directory $R exists but deploy.sh missing; remove or fix manually." >&2
  exit 1
else
  mkdir -p "$(dirname "$R")"
  git clone -b "$BR" --depth 1 "$URL" "$R"
fi
"""
            code, out, err = run_remote(client, script, dry_run=False)
            if code != 0:
                print(err or out, file=sys.stderr)
                sys.exit(f"Git sync failed with exit {code}")

        elif mode == "local":
            local_path = source.get("local_path")
            root = Path(local_path).expanduser().resolve() if local_path else REPO_ROOT
            if not (root / "deploy.sh").is_file():
                sys.exit(f"local_path {root} does not look like repo root (no deploy.sh)")
            tarball = pack_local_repo(root)
            tmp_tar = "/tmp/amnezia-wg-easy-bundle.tgz"
            sftp = client.open_sftp()
            try:
                upload_bytes(sftp, tarball, tmp_tar)
                rq = shlex.quote(remote_path)
                tq = shlex.quote(tmp_tar)
                script = f"""set -e
R={rq}
mkdir -p "$R"
tar -xzf {tq} -C "$R"
rm -f {tq}
"""
                code, out, err = run_remote(client, script, dry_run=False)
            finally:
                sftp.close()
            if code != 0:
                print(err or out, file=sys.stderr)
                sys.exit(f"Extract failed with exit {code}")
        else:
            sys.exit(f"Unknown source.mode: {mode}")

        sftp = client.open_sftp()
        try:
            env_remote = f"{remote_path}/.env"
            with sftp.open(env_remote, "w") as f:
                f.write(env_body.encode("utf-8"))
        finally:
            sftp.close()

        wd = shlex.quote(remote_path)
        # Stop project containers before rebuild. No -v: named volumes (e.g. amnezia-wg-data, SQLite) are preserved.
        code, out, err = run_remote(
            client,
            f"cd {wd} && docker compose --profile letsencrypt down --remove-orphans",
            dry_run=False,
        )
        if code != 0:
            print(err or out, file=sys.stderr)
            sys.exit(f"docker compose down failed with exit {code}")

        dp = shlex.quote(f"{remote_path}/deploy.sh")
        code, out, err = run_remote(
            client,
            f"chmod +x {dp} && cd {wd} && ./deploy.sh",
            dry_run=False,
        )
        print(out)
        if err:
            print(err, file=sys.stderr)
        if code != 0:
            sys.exit(f"deploy.sh exited with {code}")

        wg_port = merged.get("WG_PORT", "51820")
        panel = merged.get("PANEL_DOMAIN") or merged.get("WG_HOST", "")
        print()
        print("Done.")
        print(f"  Panel URL: https://{panel}/")
        print(f"  VPN endpoint: {merged.get('WG_HOST', '?')}:{wg_port} (UDP)")
        print("  Ensure firewall: 80/tcp, 443/tcp, and WG_PORT/udp. DNS A/AAAA for PANEL_DOMAIN if using Let's Encrypt.")
    finally:
        client.close()


if __name__ == "__main__":
    main()
