#!/usr/bin/env python3
"""
Remote install: YAML config -> .env on server -> ./deploy.sh over SSH.
"""
from __future__ import annotations

import argparse
import fnmatch
import io
import os
import re
import shlex
import sys
import tarfile
from pathlib import Path
from typing import Any

import paramiko
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
REMOTE_DEPLOY_DIR = Path(__file__).resolve().parent
ENV_EXAMPLE = REPO_ROOT / ".env.example"
# * SSH TCP connect timeout (seconds). Keep low; no artificial sleeps in this script.
SSH_CONNECT_TIMEOUT_SEC = 5

ENV_SUBST_PATTERN = re.compile(r"\$\{ENV:([^}]+)\}")


def _safe_write(stream: Any, text: str) -> None:
    """Avoid UnicodeEncodeError on Windows consoles when remote output has non-ASCII."""
    if not text:
        return
    if not text.endswith("\n"):
        text += "\n"
    enc = getattr(stream, "encoding", None) or "utf-8"
    buf = getattr(stream, "buffer", None)
    try:
        if buf is not None:
            buf.write(text.encode(enc, errors="replace"))
        else:
            stream.write(text.encode(enc, errors="replace").decode(enc, errors="replace"))
    except OSError:
        stream.write(text.encode("ascii", errors="replace").decode("ascii"))

# Paths excluded when packing local source (relative to repo root)
TAR_EXCLUDE_NAMES = {
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    "node_modules",
    ".cursor",
}
TAR_EXCLUDE_GLOBS = ("*.pyc", "*.pyo", ".env")


def expand_env_vars(obj: Any, environ: dict[str, str] | None = None) -> Any:
    environ = environ or os.environ

    def subst(s: str) -> str:
        def repl(m: re.Match[str]) -> str:
            key = m.group(1).strip()
            if key not in environ:
                raise KeyError(f"Environment variable {key!r} required by config (${{ENV:{key}}})")
            return environ[key]

        return ENV_SUBST_PATTERN.sub(repl, s)

    if isinstance(obj, str):
        return subst(obj)
    if isinstance(obj, dict):
        return {k: expand_env_vars(v, environ) for k, v in obj.items()}
    if isinstance(obj, list):
        return [expand_env_vars(x, environ) for x in obj]
    return obj


def parse_env_example(path: Path) -> tuple[list[str], dict[str, str]]:
    order: list[str] = []
    defaults: dict[str, str] = {}
    text = path.read_text(encoding="utf-8")
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "=" in stripped:
            key, _, val = stripped.partition("=")
            key = key.strip()
            order.append(key)
            defaults[key] = val.rstrip("\r")
    return order, defaults


def merge_env(order: list[str], defaults: dict[str, str], overrides: dict[str, Any]) -> dict[str, str]:
    merged = dict(defaults)
    for k, v in overrides.items():
        if v is None:
            continue
        key = str(k).strip().upper()
        merged[key] = str(v).strip() if isinstance(v, (str, int, float)) else str(v)
    return merged


def render_env_file(order: list[str], merged: dict[str, str]) -> str:
    lines: list[str] = [
        "# Generated by remote-deploy/install.py. Do not edit on server; re-run install from your machine.",
        "",
    ]
    seen = set()
    for key in order:
        if key in merged:
            lines.append(f"{key}={merged[key]}")
            seen.add(key)
    for key in sorted(merged.keys()):
        if key not in seen:
            lines.append(f"{key}={merged[key]}")
    lines.append("")
    return "\n".join(lines)


def should_exclude_tar(path: Path, repo_root: Path) -> bool:
    try:
        rel = path.relative_to(repo_root)
    except ValueError:
        return True
    parts = rel.parts
    if parts and parts[0] == "remote-deploy":
        return True
    for p in parts:
        if p in TAR_EXCLUDE_NAMES:
            return True
    name = path.name
    for g in TAR_EXCLUDE_GLOBS:
        if fnmatch.fnmatch(name, g):
            return True
    return False


def pack_local_repo(repo_root: Path) -> bytes:
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for root, dirs, files in os.walk(repo_root, topdown=True):
            root_path = Path(root)
            dirs[:] = [
                d
                for d in dirs
                if d not in TAR_EXCLUDE_NAMES
                and not should_exclude_tar(root_path / d, repo_root)
            ]
            for name in files:
                p = root_path / name
                if should_exclude_tar(p, repo_root):
                    continue
                arc = p.relative_to(repo_root)
                tar.add(p, arcname=str(arc).replace("\\", "/"))
    return buf.getvalue()


def load_private_key(path: Path) -> paramiko.PKey:
    path = path.expanduser()
    if not path.is_file():
        raise FileNotFoundError(f"SSH key not found: {path}")
    last_err: Exception | None = None
    for cls in (
        paramiko.Ed25519Key,
        paramiko.ECDSAKey,
        paramiko.RSAKey,
    ):
        try:
            return cls.from_private_key_file(str(path))
        except Exception as e:
            last_err = e
            continue
    raise RuntimeError(f"Cannot load private key {path}: {last_err}")


def connect_ssh(cfg: dict[str, Any]) -> paramiko.SSHClient:
    ssh_cfg = cfg["ssh"]
    host = ssh_cfg["host"]
    port = int(ssh_cfg.get("port", 22))
    user = ssh_cfg["user"]
    password = ssh_cfg.get("password")
    env_pw = ssh_cfg.get("ssh_password_env")
    if env_pw:
        password = os.environ.get(env_pw)
    ident = ssh_cfg.get("identity_file")

    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    kwargs: dict[str, Any] = {
        "hostname": host,
        "port": port,
        "username": user,
        "timeout": SSH_CONNECT_TIMEOUT_SEC,
        "allow_agent": True,
        "look_for_keys": not ident and not password,
    }
    if ident:
        kwargs["pkey"] = load_private_key(Path(str(ident)))
    elif password:
        kwargs["password"] = password
    else:
        raise SystemExit("ssh: set identity_file, password, or ssh_password_env (with env var set)")

    client.connect(**kwargs)
    return client


def run_remote(
    client: paramiko.SSHClient,
    cmd: str,
    *,
    dry_run: bool,
) -> tuple[int, str, str]:
    if dry_run:
        print(f"[dry-run] exec: {cmd}")
        return 0, "", ""
    stdin, stdout, stderr = client.exec_command(cmd, get_pty=True)
    out = stdout.read().decode("utf-8", errors="replace")
    err = stderr.read().decode("utf-8", errors="replace")
    code = stdout.channel.recv_exit_status()
    return code, out, err


def upload_bytes(sftp: paramiko.SFTPClient, data: bytes, remote_path: str) -> None:
    with sftp.open(remote_path, "wb") as f:
        f.write(data)


def parse_target_ports(merged: dict[str, str]) -> tuple[int, int, int]:
    """WG UDP, panel HTTP TCP (host), panel HTTPS TCP (host)."""

    def g(key: str, default: str) -> int:
        raw = merged.get(key)
        if raw is None or str(raw).strip() == "":
            raw = default
        try:
            v = int(str(raw).strip(), 10)
        except ValueError as e:
            raise SystemExit(f"Invalid {key}: expected integer port, got {raw!r}") from e
        if not (1 <= v <= 65535):
            raise SystemExit(f"Invalid {key}: must be 1-65535, got {v}")
        return v

    return (
        g("WG_PORT", "51820"),
        g("PANEL_HTTP_PORT", "80"),
        g("PANEL_HTTPS_PORT", "443"),
    )


def build_remote_port_preflight_script(remote_path: str, wg: int, http: int, https: int) -> str:
    """Bash: verify target ports are free or owned by this compose project (before compose down)."""
    rq = shlex.quote(remote_path)
    return f"""set -e
R={rq}
WG={wg}
HTTP={http}
HTTPS={https}
cd "$R" || {{ echo "ERROR: cannot cd to $R" >&2; exit 1; }}

listening_tcp() {{
  local p="$1"
  if ss -tln 2>/dev/null | awk '{{print $4}}' | grep -qE ":${{p}}$|\\[::\\]:${{p}}$"; then
    return 0
  fi
  return 1
}}

listening_udp() {{
  local p="$1"
  if ss -uln 2>/dev/null | awk '{{print $4}}' | grep -qE ":${{p}}$|\\[::\\]:${{p}}$"; then
    return 0
  fi
  return 1
}}

compose_up() {{
  local n
  n=$(docker compose -f docker-compose.yml ps -q 2>/dev/null | wc -l)
  if [ "${{n:-0}}" -ge 1 ]; then
    return 0
  fi
  return 1
}}

check_tcp() {{
  local inner="$1"
  local hostport="$2"
  if ! listening_tcp "$hostport"; then
    return 0
  fi
  if ! compose_up; then
    echo "ERROR: TCP port $hostport is in use, but this project's docker compose stack is not running in $R." >&2
    ss -tlnp 2>/dev/null | grep -E ":${{hostport}}\\s" || true
    return 1
  fi
  out=$(docker compose -f docker-compose.yml port nginx "$inner" 2>/dev/null || true)
  if echo "$out" | grep -qE ":${{hostport}}($|\\s)"; then
    return 0
  fi
  echo "ERROR: TCP port $hostport is in use (not published by this compose nginx $inner)." >&2
  ss -tlnp 2>/dev/null | grep -E ":${{hostport}}\\s" || true
  return 1
}}

check_udp() {{
  local hostport="$1"
  if ! listening_udp "$hostport"; then
    return 0
  fi
  if ! compose_up; then
    echo "ERROR: UDP port $hostport is in use, but this project's docker compose stack is not running in $R." >&2
    ss -ulnp 2>/dev/null | grep -E ":${{hostport}}\\s" || true
    return 1
  fi
  out=$(docker compose -f docker-compose.yml port amnezia-wg-easy "${{hostport}}/udp" 2>/dev/null || true)
  if echo "$out" | grep -qE ":${{hostport}}($|\\s)"; then
    return 0
  fi
  echo "ERROR: UDP port $hostport is in use (not published by this compose amnezia-wg-easy)." >&2
  ss -ulnp 2>/dev/null | grep -E ":${{hostport}}\\s" || true
  return 1
}}

check_tcp "443/tcp" "$HTTPS"
check_tcp "80/tcp" "$HTTP"
check_udp "$WG"
echo "Port preflight OK (UDP WG $WG, TCP HTTP $HTTP, TCP HTTPS $HTTPS)."
"""


def resolve_config_path(explicit: Path | None) -> Path:
    """Default: first existing file among config.yaml, deploy-runtime.yaml in remote-deploy/."""
    if explicit is not None:
        return explicit
    for name in ("config.yaml", "deploy-runtime.yaml"):
        p = REMOTE_DEPLOY_DIR / name
        if p.is_file():
            return p
    return REMOTE_DEPLOY_DIR / "config.yaml"


def mask_env_for_print(text: str) -> str:
    out_lines = []
    for line in text.splitlines():
        if "=" not in line or line.strip().startswith("#"):
            out_lines.append(line)
            continue
        k, _, _ = line.partition("=")
        key = k.strip().upper()
        if any(x in key for x in ("PASSWORD", "SECRET", "TOKEN", "PRIVATE", "PRESHARED")):
            out_lines.append(f"{k.strip()}=(hidden)")
        else:
            out_lines.append(line)
    return "\n".join(out_lines) + ("\n" if text.endswith("\n") else "")


def _topology_key_is_sensitive(key: str) -> bool:
    u = key.upper()
    return any(x in u for x in ("PASSWORD", "SECRET", "TOKEN", "PRIVATE", "PRESHARED", "KEY"))


def mask_topology_for_print(obj: Any, parent_key: str = "") -> Any:
    """Mask values when the dict key looks like a secret (e.g. preshared_key)."""
    if isinstance(obj, dict):
        return {k: mask_topology_for_print(v, k) for k, v in obj.items()}
    if isinstance(obj, list):
        return [mask_topology_for_print(x, parent_key) for x in obj]
    if parent_key and _topology_key_is_sensitive(parent_key):
        return "(hidden)"
    return obj


def get_topology(cfg: dict[str, Any]) -> dict[str, Any] | None:
    raw = cfg.get("topology")
    if raw is None:
        return None
    if not isinstance(raw, dict):
        sys.exit("Invalid config: topology must be a mapping or omitted.")
    return raw


def print_topology_informational(topology: dict[str, Any]) -> None:
    print("--- Cascade / double VPN (informational) ---", flush=True)
    masked = mask_topology_for_print(topology)
    print(yaml.safe_dump(masked, allow_unicode=True, default_flow_style=False).rstrip(), flush=True)
    print(
        "This block documents intent only; install.py does not configure cascade routing or a second hub.",
        flush=True,
    )


def print_topology_dry_run_extra_steps(topology: dict[str, Any]) -> None:
    mode = str(topology.get("mode", "unspecified")).strip().lower()
    print("[dry-run] Cascade / double VPN (manual steps; not executed):", flush=True)
    print(f"  7. (manual) topology.mode={mode!r} - documentation only; no remote commands for cascade.", flush=True)
    if mode == "manual_site_to_site":
        print(
            "  8. (manual) On ENTRY: route/NAT toward EXIT per docs/cascade-vpn-modes.md; "
            "site-to-site tunnel is outside WG-Easy.",
            flush=True,
        )
        print(
            "  9. (manual) Ensure distinct WG subnets per hub; align firewall/AllowedIPs on each panel.",
            flush=True,
        )
    elif mode == "client_double_tunnel":
        print(
            "  8. (manual) Client: two tunnels; tune MTU and split-tunnel (AllowedIPs) to avoid routing loops.",
            flush=True,
        )
        print("  9. (manual) See docs/cascade-vpn-modes.md (DPI/MTU).", flush=True)
    elif mode == "single_exit_only":
        print(
            "  8. (manual) Single-exit topology: no cascade automation; verify env matches this host only.",
            flush=True,
        )
    else:
        print("  8. (manual) Review topology.notes and docs/cascade-vpn-modes.md.", flush=True)


def main() -> None:
    ap = argparse.ArgumentParser(description="Deploy amnezia-wg-easy over SSH from YAML config.")
    ap.add_argument(
        "--config",
        "-c",
        type=Path,
        default=None,
        help=f"Path to YAML (default: first of {REMOTE_DEPLOY_DIR / 'config.yaml'}, "
        f"{REMOTE_DEPLOY_DIR / 'deploy-runtime.yaml'} if present, else config.yaml)",
    )
    ap.add_argument("--dry-run", action="store_true", help="Print actions and masked .env; no SSH.")
    ap.add_argument(
        "--skip-port-check",
        action="store_true",
        help="Skip remote port preflight before docker compose down (not recommended).",
    )
    args = ap.parse_args()

    config_path = resolve_config_path(args.config)
    if not config_path.is_file():
        print(f"Config not found: {config_path}", file=sys.stderr)
        print(
            f"Copy {REMOTE_DEPLOY_DIR / 'config.example.yaml'} to config.yaml or deploy-runtime.yaml and edit.",
            file=sys.stderr,
        )
        sys.exit(1)

    raw = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    try:
        cfg = expand_env_vars(raw)
    except KeyError as e:
        print(f"Config env error: {e}", file=sys.stderr)
        sys.exit(1)

    if "ssh" not in cfg or "host" not in cfg["ssh"] or "user" not in cfg["ssh"]:
        sys.exit("Invalid config: ssh.host and ssh.user are required.")

    if not ENV_EXAMPLE.is_file():
        sys.exit(f".env.example not found at {ENV_EXAMPLE} (run from repo checkout).")

    order, defaults = parse_env_example(ENV_EXAMPLE)
    env_section = cfg.get("env") or {}
    if not isinstance(env_section, dict):
        sys.exit("Invalid config: env must be a mapping.")
    merged = merge_env(order, defaults, env_section)
    env_body = render_env_file(order, merged)
    wg_p, http_p, https_p = parse_target_ports(merged)

    remote_path = cfg.get("remote", {}).get("path", "/opt/amnezia-wg-easy")
    remote_path = remote_path.rstrip("/")

    print(f"Using config: {config_path}", flush=True)
    print(
        f"--- Target ports: WG UDP {wg_p}, panel HTTP TCP {http_p}, panel HTTPS TCP {https_p} ---",
        flush=True,
    )
    print("--- Rendered .env (secrets masked in dry-run / log) ---", flush=True)
    print(mask_env_for_print(env_body), flush=True)

    topology = get_topology(cfg)
    if topology:
        print_topology_informational(topology)

    source = cfg.get("source") or {}
    mode = (source.get("mode") or "git").lower()

    if args.dry_run:
        print("[dry-run] Would connect SSH and:")
        sk = " (skipped with --skip-port-check)" if args.skip_port_check else ""
        print(
            f"  0. Port preflight on remote (ss + docker compose port){sk}: "
            f"UDP {wg_p}, TCP {http_p}/{https_p}"
        )
        print(f"  1. Ensure Docker: docker compose version")
        print(f"  2. Sync source ({mode}) -> {remote_path}")
        print(f"  3. Upload .env -> {remote_path}/.env")
        print(
            f"  4. Stop stack (this project only, volumes kept): "
            f"cd {remote_path} && docker compose -f docker-compose.yml --profile letsencrypt down --remove-orphans"
        )
        print(f"  5. Run: cd {remote_path} && chmod +x deploy.sh && ./deploy.sh")
        print(
            f"  6. Sync panel admin password from .env: "
            f"docker compose -f docker-compose.yml exec -T amnezia-wg-easy "
            f"node scripts/applyAdminPasswordFromEnv.js"
        )
        if topology:
            print_topology_dry_run_extra_steps(topology)
        return

    client = connect_ssh(cfg)
    try:
        code, out, err = run_remote(
            client,
            "docker compose version 2>/dev/null || docker compose version",
            dry_run=False,
        )
        if code != 0:
            print(err or out, file=sys.stderr)
            sys.exit(
                "Remote host: Docker Compose v2 is required (`docker compose version`). Install Docker Engine + Compose plugin."
            )

        if mode == "git":
            git_url = source.get("git_url")
            branch = source.get("branch", "master")
            if not git_url:
                sys.exit("source.git_url is required when source.mode is git")
            r = shlex.quote(remote_path)
            u = shlex.quote(str(git_url))
            b = shlex.quote(str(branch))
            script = f"""set -e
R={r}
URL={u}
BR={b}
if [ -f "$R/deploy.sh" ]; then
  cd "$R" && git fetch origin && git checkout "$BR" && git pull origin "$BR"
elif [ -d "$R" ]; then
  echo "Directory $R exists but deploy.sh missing; remove or fix manually." >&2
  exit 1
else
  mkdir -p "$(dirname "$R")"
  git clone -b "$BR" --depth 1 "$URL" "$R"
fi
"""
            code, out, err = run_remote(client, script, dry_run=False)
            if code != 0:
                print(err or out, file=sys.stderr)
                sys.exit(f"Git sync failed with exit {code}")

        elif mode == "local":
            local_path = source.get("local_path")
            root = Path(local_path).expanduser().resolve() if local_path else REPO_ROOT
            if not (root / "deploy.sh").is_file():
                sys.exit(f"local_path {root} does not look like repo root (no deploy.sh)")
            tarball = pack_local_repo(root)
            tmp_tar = "/tmp/amnezia-wg-easy-bundle.tgz"
            sftp = client.open_sftp()
            try:
                upload_bytes(sftp, tarball, tmp_tar)
                rq = shlex.quote(remote_path)
                tq = shlex.quote(tmp_tar)
                script = f"""set -e
R={rq}
mkdir -p "$R"
tar -xzf {tq} -C "$R"
rm -f {tq}
"""
                code, out, err = run_remote(client, script, dry_run=False)
            finally:
                sftp.close()
            if code != 0:
                print(err or out, file=sys.stderr)
                sys.exit(f"Extract failed with exit {code}")
        else:
            sys.exit(f"Unknown source.mode: {mode}")

        if not args.skip_port_check:
            pf = build_remote_port_preflight_script(remote_path, wg_p, http_p, https_p)
            print("--- Remote port preflight ---", flush=True)
            code, out, err = run_remote(client, pf, dry_run=False)
            if out:
                _safe_write(sys.stdout, out)
            if err:
                _safe_write(sys.stderr, err)
            if code != 0:
                sys.exit(
                    f"Port preflight failed (exit {code}). "
                    "Free the ports or fix conflicts; or use --skip-port-check if you accept the risk."
                )
        else:
            print("[install] Skipping port preflight (--skip-port-check).", flush=True)

        sftp = client.open_sftp()
        try:
            env_remote = f"{remote_path}/.env"
            with sftp.open(env_remote, "w") as f:
                f.write(env_body.encode("utf-8"))
        finally:
            sftp.close()

        wd = shlex.quote(remote_path)
        # Only this compose project (cwd + docker-compose.yml). No -v: DB volumes kept.
        code, out, err = run_remote(
            client,
            f"cd {wd} && docker compose -f docker-compose.yml --profile letsencrypt down --remove-orphans",
            dry_run=False,
        )
        if code != 0:
            _safe_write(sys.stderr, err or out)
            sys.exit(f"docker compose down failed with exit {code}")

        dp = shlex.quote(f"{remote_path}/deploy.sh")
        code, out, err = run_remote(
            client,
            f"chmod +x {dp} && cd {wd} && ./deploy.sh",
            dry_run=False,
        )
        _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)
        if code != 0:
            sys.exit(f"deploy.sh exited with {code}")

        code, out, err = run_remote(
            client,
            f"cd {wd} && docker compose -f docker-compose.yml exec -T amnezia-wg-easy node scripts/applyAdminPasswordFromEnv.js",
            dry_run=False,
        )
        _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)
        if code != 0:
            sys.exit(
                f"applyAdminPasswordFromEnv.js exited with {code} "
                "(check ADMIN_USERNAME matches an active panel user; see stderr above)"
            )

        wg_port = merged.get("WG_PORT", "51820")
        https_port = merged.get("PANEL_HTTPS_PORT", "443")
        http_port = merged.get("PANEL_HTTP_PORT", "80")
        panel = merged.get("PANEL_DOMAIN") or merged.get("WG_HOST", "")
        print()
        print("Done.")
        url_suffix = "" if str(https_port) == "443" else f":{https_port}"
        print(f"  Panel URL: https://{panel}{url_suffix}/")
        print(f"  VPN endpoint: {merged.get('WG_HOST', '?')}:{wg_port} (UDP)")
        print(
            f"  Ensure firewall: TCP {http_port} (HTTP), TCP {https_port} (HTTPS), "
            f"UDP {wg_port} (VPN). Cloud SG / external firewall: open these manually if needed."
        )
        print("  DNS A/AAAA for PANEL_DOMAIN if using Let's Encrypt.")
    finally:
        client.close()


if __name__ == "__main__":
    main()
