#!/usr/bin/env python3
"""
Cascade remote deploy orchestrator:
- S2: exit-core only (amneziavpn/amneziawg-go, no panel) — see exit-core/README.md.
- S1: full panel + awg-cascade inside the panel container (AmneziaWG, same obfuscation as awg0).
- Host hooks: NAT/forward on exit only (interface exit-cascade).
"""
from __future__ import annotations

import argparse
import fnmatch
import ipaddress
import io
import os
import re
import shlex
import sys
import tarfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import paramiko
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
WORK_DIR = Path(__file__).resolve().parent
EXIT_CORE_DIR = WORK_DIR / "exit-core"
ENV_EXAMPLE = REPO_ROOT / ".env.example"
SSH_CONNECT_TIMEOUT_SEC = 5

REMOTE_TIMEOUT_COMPOSE_DOWN = 300
REMOTE_TIMEOUT_PREFLIGHT = 120
REMOTE_TIMEOUT_GIT = 600
REMOTE_TIMEOUT_DEPLOY = 7200
REMOTE_TIMEOUT_ADMIN_SCRIPT = 120
REMOTE_TIMEOUT_DOCKER_CHECK = 60
REMOTE_TIMEOUT_HOOKS = 180
REMOTE_TIMEOUT_TUNNEL = 240
REMOTE_TIMEOUT_SYNC = 300

ENV_SUBST_PATTERN = re.compile(r"\$\{ENV:([^}]+)\}")
TAR_EXCLUDE_NAMES = {".git", ".venv", "venv", "__pycache__", ".pytest_cache", "node_modules", ".cursor"}
TAR_EXCLUDE_GLOBS = ("*.pyc", "*.pyo", ".env")

# S2 exit-core AmneziaWG UDP — avoid default WireGuard 51820/51821.
CASCADE_DEFAULT_LISTEN_PORT = 8443


def _safe_write(stream: Any, text: str) -> None:
    if not text:
        return
    if not text.endswith("\n"):
        text += "\n"
    enc = getattr(stream, "encoding", None) or "utf-8"
    buf = getattr(stream, "buffer", None)
    try:
        if buf is not None:
            buf.write(text.encode(enc, errors="replace"))
        else:
            stream.write(text.encode(enc, errors="replace").decode(enc, errors="replace"))
    except OSError:
        stream.write(text.encode("ascii", errors="replace").decode("ascii"))


def expand_env_vars(obj: Any, environ: dict[str, str] | None = None) -> Any:
    environ = environ or os.environ

    def subst(s: str) -> str:
        def repl(m: re.Match[str]) -> str:
            key = m.group(1).strip()
            if key not in environ:
                raise KeyError(f"Environment variable {key!r} required by config (${{ENV:{key}}})")
            return environ[key]

        return ENV_SUBST_PATTERN.sub(repl, s)

    if isinstance(obj, str):
        return subst(obj)
    if isinstance(obj, dict):
        return {k: expand_env_vars(v, environ) for k, v in obj.items()}
    if isinstance(obj, list):
        return [expand_env_vars(x, environ) for x in obj]
    return obj


def parse_env_example(path: Path) -> tuple[list[str], dict[str, str]]:
    order: list[str] = []
    defaults: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, _, v = s.partition("=")
        k = k.strip()
        order.append(k)
        defaults[k] = v.rstrip("\r")
    return order, defaults


def merge_env(order: list[str], defaults: dict[str, str], overrides: dict[str, Any]) -> dict[str, str]:
    merged = dict(defaults)
    for k, v in overrides.items():
        if v is None:
            continue
        merged[str(k).strip().upper()] = str(v).strip()
    return merged


def render_env_file(order: list[str], merged: dict[str, str], tag: str) -> str:
    lines = [f"# Generated by remote-deploy-cascade/install.py ({tag}).", ""]
    seen: set[str] = set()
    for key in order:
        if key in merged:
            lines.append(f"{key}={merged[key]}")
            seen.add(key)
    for key in sorted(merged.keys()):
        if key not in seen:
            lines.append(f"{key}={merged[key]}")
    lines.append("")
    return "\n".join(lines)


def mask_env_for_print(text: str) -> str:
    out: list[str] = []
    for line in text.splitlines():
        if "=" not in line or line.strip().startswith("#"):
            out.append(line)
            continue
        k, _, _ = line.partition("=")
        ku = k.strip().upper()
        if any(x in ku for x in ("PASSWORD", "SECRET", "TOKEN", "PRIVATE", "PRESHARED")):
            out.append(f"{k.strip()}=(hidden)")
        else:
            out.append(line)
    return "\n".join(out) + ("\n" if text.endswith("\n") else "")


def should_exclude_tar(path: Path, repo_root: Path) -> bool:
    try:
        rel = path.relative_to(repo_root)
    except ValueError:
        return True
    parts = rel.parts
    if parts and parts[0].startswith("remote-deploy"):
        return True
    for p in parts:
        if p in TAR_EXCLUDE_NAMES:
            return True
    return any(fnmatch.fnmatch(path.name, g) for g in TAR_EXCLUDE_GLOBS)


def pack_local_repo(repo_root: Path) -> bytes:
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for root, dirs, files in os.walk(repo_root, topdown=True):
            rp = Path(root)
            dirs[:] = [d for d in dirs if d not in TAR_EXCLUDE_NAMES and not should_exclude_tar(rp / d, repo_root)]
            for f in files:
                p = rp / f
                if should_exclude_tar(p, repo_root):
                    continue
                tar.add(p, arcname=str(p.relative_to(repo_root)).replace("\\", "/"))
    return buf.getvalue()


def _truthy(v: Any) -> bool:
    if v is True:
        return True
    if v is False or v is None:
        return False
    return str(v).strip().lower() in ("1", "true", "yes", "on")


def pack_exit_core() -> bytes:
    if not EXIT_CORE_DIR.is_dir():
        raise SystemExit(f"exit-core bundle missing: {EXIT_CORE_DIR}")
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for name in ("docker-compose.yml", "README.md"):
            p = EXIT_CORE_DIR / name
            if p.is_file():
                tar.add(p, arcname=name)
    return buf.getvalue()


def load_private_key(path: Path) -> paramiko.PKey:
    p = path.expanduser()
    if not p.is_file():
        raise FileNotFoundError(f"SSH key not found: {p}")
    last: Exception | None = None
    for cls in (paramiko.Ed25519Key, paramiko.ECDSAKey, paramiko.RSAKey):
        try:
            return cls.from_private_key_file(str(p))
        except Exception as e:
            last = e
    raise RuntimeError(f"Cannot load private key {p}: {last}")


def connect_ssh(ssh_cfg: dict[str, Any]) -> paramiko.SSHClient:
    host = ssh_cfg["host"]
    port = int(ssh_cfg.get("port", 22))
    user = ssh_cfg["user"]
    password = ssh_cfg.get("password")
    env_pw = ssh_cfg.get("ssh_password_env")
    if env_pw:
        password = os.environ.get(str(env_pw))
    ident = ssh_cfg.get("identity_file")

    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    kwargs: dict[str, Any] = {
        "hostname": host,
        "port": port,
        "username": user,
        "timeout": SSH_CONNECT_TIMEOUT_SEC,
        "allow_agent": True,
        "look_for_keys": not ident and not password,
    }
    if ident:
        kwargs["pkey"] = load_private_key(Path(str(ident)))
    elif password:
        kwargs["password"] = password
    else:
        raise SystemExit("ssh: set identity_file, password, or ssh_password_env (with env var set)")

    client.connect(**kwargs)
    return client


def run_remote(
    client: paramiko.SSHClient,
    cmd: str,
    *,
    dry_run: bool,
    timeout_sec: int,
) -> tuple[int, str, str]:
    if dry_run:
        print(f"[dry-run] exec ({timeout_sec}s): {cmd[:280]}{'...' if len(cmd) > 280 else ''}")
        return 0, "", ""

    wrapped = (
        f"if command -v timeout >/dev/null 2>&1; then "
        f"timeout {timeout_sec} sh -c {shlex.quote(cmd)}; "
        f"else sh -c {shlex.quote(cmd)}; fi"
    )
    tr = client.get_transport()
    if tr and tr.sock is not None:
        tr.sock.settimeout(float(timeout_sec + 90))
    _, stdout, stderr = client.exec_command(wrapped, get_pty=False)
    out = stdout.read().decode("utf-8", errors="replace")
    err = stderr.read().decode("utf-8", errors="replace")
    code = stdout.channel.recv_exit_status()
    return code, out, err


def parse_target_ports(merged_env: dict[str, str]) -> tuple[int, int, int]:
    def g(key: str, default: str) -> int:
        raw = merged_env.get(key, default).strip()
        try:
            v = int(raw, 10)
        except ValueError as e:
            raise SystemExit(f"Invalid {key}: {raw!r}") from e
        if v < 1 or v > 65535:
            raise SystemExit(f"Invalid {key}: {v}")
        return v

    return g("WG_PORT", "51820"), g("PANEL_HTTP_PORT", "80"), g("PANEL_HTTPS_PORT", "443")


def build_compose_down_script(remote_path: str, *, wipe_db: bool) -> str:
    rq = shlex.quote(remote_path)
    wipe_flag = "1" if wipe_db else "0"
    return f"""set -e
R={rq}
WIPE_DB={wipe_flag}
if [ ! -d "$R" ] || [ ! -f "$R/docker-compose.yml" ]; then
  echo "[install] No existing stack at $R (skip compose down)."
  exit 0
fi
cd "$R"
docker compose -f docker-compose.yml --profile letsencrypt down --remove-orphans || true
docker compose -f docker-compose.yml down --remove-orphans || true
if [ "$WIPE_DB" = "1" ]; then
  for v in $(docker compose -f docker-compose.yml config --volumes 2>/dev/null || true); do
    case "$v" in
      *amnezia-wg-data*)
        docker volume rm "$v" >/dev/null 2>&1 || true
        ;;
    esac
  done
  echo "[install] DB volume cleanup requested (--wipe-db)."
fi
echo "[install] This project stack stopped."
"""


def build_port_preflight_script(remote_path: str, wg: int, http: int, https: int) -> str:
    rq = shlex.quote(remote_path)
    return f"""set -e
R={rq}
WG={wg}
HTTP={http}
HTTPS={https}
cd "$R" || {{ echo "ERROR: cannot cd to $R" >&2; exit 1; }}

check_tcp() {{
  local p="$1"
  if ss -tln 2>/dev/null | awk '{{print $4}}' | grep -qE ":${{p}}$|\\[::\\]:${{p}}$"; then
    echo "ERROR: TCP $p already in use." >&2
    ss -tlnp 2>/dev/null | grep -E ":${{p}}\\s" || true
    return 1
  fi
  return 0
}}
check_udp() {{
  local p="$1"
  if ss -uln 2>/dev/null | awk '{{print $4}}' | grep -qE ":${{p}}$|\\[::\\]:${{p}}$"; then
    echo "ERROR: UDP $p already in use." >&2
    ss -ulnp 2>/dev/null | grep -E ":${{p}}\\s" || true
    return 1
  fi
  return 0
}}
check_tcp "$HTTPS"
check_tcp "$HTTP"
check_udp "$WG"
echo "Port preflight OK (UDP $WG, TCP $HTTP/$HTTPS)."
"""


def build_compose_down_exit_core_script(remote_path: str, *, wipe_cascade: bool) -> str:
    rq = shlex.quote(remote_path)
    wipe = "1" if wipe_cascade else "0"
    return f"""set -e
R={rq}
WIPE={wipe}
if [ -d "$R" ] && [ -f "$R/docker-compose.yml" ]; then
  cd "$R"
  docker compose -f docker-compose.yml down --remove-orphans || true
fi
if [ "$WIPE" = "1" ]; then
  docker volume rm amnezia-cascade-exit_exit-cascade-config 2>/dev/null || true
  echo "[install] exit-cascade Docker volume removed (--wipe-cascade)."
fi
echo "[install] exit-core stack stopped."
"""


def build_udp_port_preflight_script(udp_port: int) -> str:
    return f"""set -e
WG={int(udp_port)}
check_udp() {{
  local p="$1"
  if ss -uln 2>/dev/null | awk '{{print $4}}' | grep -qE ":${{p}}$|\\[::\\]:${{p}}$"; then
    echo "ERROR: UDP $p already in use." >&2
    ss -ulnp 2>/dev/null | grep -E ":${{p}}\\s" || true
    return 1
  fi
  return 0
}}
check_udp "$WG"
echo "Port preflight OK (UDP $WG)."
"""


@dataclass
class HostSpec:
    name: str
    ssh: dict[str, Any]
    source: dict[str, Any]
    remote_path: str
    merged_env: dict[str, str]
    env_body: str
    wg_port: int
    http_port: int
    https_port: int
    network: dict[str, Any]
    is_exit_core: bool = False


def parse_host_spec(
    name: str,
    cfg: dict[str, Any],
    common_source: dict[str, Any],
    order: list[str],
    defaults: dict[str, str],
) -> HostSpec:
    section = cfg.get(name) or {}
    if not isinstance(section, dict):
        raise SystemExit(f"Invalid {name}: expected mapping.")
    ssh_cfg = section.get("ssh")
    if not isinstance(ssh_cfg, dict) or "host" not in ssh_cfg or "user" not in ssh_cfg:
        raise SystemExit(f"Invalid {name}.ssh: host/user required.")

    source = section.get("source") if isinstance(section.get("source"), dict) else common_source
    if not isinstance(source, dict):
        source = {}
    remote = section.get("remote") or {}
    if not isinstance(remote, dict):
        raise SystemExit(f"Invalid {name}.remote")
    remote_path = str(remote.get("path") or f"/opt/amnezia-wg-easy-{name}").rstrip("/")

    env_overrides = section.get("env") or {}
    if not isinstance(env_overrides, dict):
        raise SystemExit(f"Invalid {name}.env: mapping expected")
    network = section.get("network") or {}
    if not isinstance(network, dict):
        raise SystemExit(f"Invalid {name}.network: mapping expected")

    is_exit_core = name == "exit" and (
        _truthy(section.get("core")) or str(section.get("mode", "")).strip().lower() == "core"
    )
    if is_exit_core:
        rpath = str(remote.get("path") or "/opt/amnezia-cascade-exit").rstrip("/")
        try:
            listen = int(str(network.get("cascade_listen_port", CASCADE_DEFAULT_LISTEN_PORT)))
        except ValueError as e:
            raise SystemExit("exit.network.cascade_listen_port must be an integer") from e
        if listen < 1 or listen > 65535:
            raise SystemExit("exit.network.cascade_listen_port out of range")
        return HostSpec(
            name=name,
            ssh=ssh_cfg,
            source={},
            remote_path=rpath,
            merged_env={},
            env_body="# exit-core (AmneziaWG only — no panel .env)\n\n",
            wg_port=listen,
            http_port=80,
            https_port=443,
            network=network,
            is_exit_core=True,
        )

    merged = merge_env(order, defaults, env_overrides)

    # Cascade mode: disable entry-side default masquerade in awg PostUp.
    if name == "entry":
        client_cidrs = _cidr_list(network.get("client_cidrs"), required=True, ctx="entry.network.client_cidrs")
        client_cidr = client_cidrs[0]
        wg_port = str(merged.get("WG_PORT", "51820")).strip() or "51820"
        cascade_fwd = ""
        if _truthy(network.get("cascade_enabled")):
            cascade_fwd = (
                "nft add rule inet amnezia_wg_base forward_awg0_base iifname \"awg-cascade\" accept ; "
                "nft add rule inet amnezia_wg_base forward_awg0_base oifname \"awg-cascade\" accept ; "
                "nft add rule inet amnezia_wg_base forward_awg0_base iifname \"awg0\" oifname \"awg-cascade\" accept ; "
                "nft add rule inet amnezia_wg_base forward_awg0_base iifname \"awg-cascade\" oifname \"awg0\" accept"
            )
        merged["WG_POST_UP"] = (
            "nft delete table inet amnezia_wg_base 2>/dev/null || true ; "
            "nft add table inet amnezia_wg_base ; "
            "nft add chain inet amnezia_wg_base input_awg0 '{ type filter hook input priority -100; policy accept; }' ; "
            f"nft add rule inet amnezia_wg_base input_awg0 udp dport {wg_port} accept ; "
            "nft add chain inet amnezia_wg_base forward_awg0_base '{ type filter hook forward priority 0; policy accept; }' ; "
            "nft add rule inet amnezia_wg_base forward_awg0_base iifname \"awg0\" accept ; "
            "nft add rule inet amnezia_wg_base forward_awg0_base oifname \"awg0\" accept ; "
            f"nft add rule inet amnezia_wg_base forward_awg0_base iifname \"awg0\" ip saddr {client_cidr} accept"
            + (f" ; {cascade_fwd}" if cascade_fwd else "")
        )
        merged["WG_POST_DOWN"] = "nft delete table inet amnezia_wg_base 2>/dev/null || true"

        if _truthy(network.get("cascade_enabled")):
            ei = str(network.get("cascade_entry_ip", "172.31.255.1")).strip()
            xip = str(network.get("cascade_exit_ip", "172.31.255.2")).strip()
            plen = str(network.get("cascade_prefix_len", "30")).strip()
            listen = str(network.get("cascade_listen_port", str(CASCADE_DEFAULT_LISTEN_PORT))).strip()
            ex_host = str(((cfg.get("exit") or {}).get("ssh") or {}).get("host", "")).strip()
            endpoint = str(network.get("cascade_exit_endpoint", "")).strip()
            if not endpoint and ex_host:
                endpoint = f"{ex_host}:{listen}"
            merged["WG_CASCADE_ENABLED"] = "true"
            merged["WG_CASCADE_ADDRESS"] = f"{ei}/{plen}"
            merged["WG_CASCADE_EXIT_TUNNEL_IP"] = xip
            if endpoint:
                merged["WG_CASCADE_EXIT_ENDPOINT"] = endpoint
            pub = str(network.get("cascade_exit_public_key", "")).strip()
            if pub:
                merged["WG_CASCADE_EXIT_PUBLIC_KEY"] = pub
            merged["WG_CASCADE_CLIENT_SUBNET"] = client_cidr

    env_body = render_env_file(order, merged, tag=name)
    wg, http, https = parse_target_ports(merged)

    return HostSpec(
        name=name,
        ssh=ssh_cfg,
        source=source,
        remote_path=remote_path,
        merged_env=merged,
        env_body=env_body,
        wg_port=wg,
        http_port=http,
        https_port=https,
        network=network,
        is_exit_core=False,
    )


def sync_source(client: paramiko.SSHClient, spec: HostSpec, dry_run: bool) -> None:
    mode = str(spec.source.get("mode") or "git").lower()
    if mode == "git":
        git_url = spec.source.get("git_url")
        if not git_url:
            raise SystemExit(f"{spec.name}: source.git_url is required for git mode")
        branch = str(spec.source.get("branch") or "master")
        r = shlex.quote(spec.remote_path)
        u = shlex.quote(str(git_url))
        b = shlex.quote(branch)
        script = f"""set -e
R={r}
URL={u}
BR={b}
if [ -f "$R/deploy.sh" ]; then
  cd "$R" && git fetch origin && git checkout "$BR" && git pull origin "$BR"
elif [ -d "$R" ]; then
  echo "Directory $R exists but deploy.sh missing; remove or fix manually." >&2
  exit 1
else
  mkdir -p "$(dirname "$R")"
  git clone -b "$BR" --depth 1 "$URL" "$R"
fi
"""
        code, out, err = run_remote(client, script, dry_run=dry_run, timeout_sec=REMOTE_TIMEOUT_GIT)
        if out:
            _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)
        if code == 124:
            raise SystemExit(f"{spec.name}: git sync timeout")
        if code != 0:
            raise SystemExit(f"{spec.name}: git sync failed (exit {code})")
        return

    if mode == "local":
        local_path = spec.source.get("local_path")
        root = Path(local_path).expanduser().resolve() if local_path else REPO_ROOT
        if not (root / "deploy.sh").is_file():
            raise SystemExit(f"{spec.name}: local_path {root} has no deploy.sh")
        if dry_run:
            print(f"[dry-run] {spec.name}: pack and upload local source from {root}")
            return
        tarball = pack_local_repo(root)
        tmp_tar = "/tmp/amnezia-wg-easy-cascade-bundle.tgz"
        sftp = client.open_sftp()
        try:
            with sftp.open(tmp_tar, "wb") as f:
                f.write(tarball)
        finally:
            sftp.close()
        rq = shlex.quote(spec.remote_path)
        tq = shlex.quote(tmp_tar)
        script = f"""set -e
R={rq}
mkdir -p "$R"
tar -xzf {tq} -C "$R"
rm -f {tq}
"""
        code, out, err = run_remote(client, script, dry_run=False, timeout_sec=REMOTE_TIMEOUT_GIT)
        if out:
            _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)
        if code == 124:
            raise SystemExit(f"{spec.name}: local extract timeout")
        if code != 0:
            raise SystemExit(f"{spec.name}: local extract failed (exit {code})")
        return

    raise SystemExit(f"{spec.name}: unknown source.mode={mode!r}")


def deploy_exit_core_stack(
    spec: HostSpec,
    *,
    dry_run: bool,
    skip_port_check: bool,
    wipe_cascade: bool,
) -> None:
    """S2: minimal amneziawg-go stack only (no panel). Does not touch old panel paths."""
    print(f"\n=== Deploy EXIT-CORE ({spec.ssh['host']}) ===", flush=True)
    print(f"UDP cascade listen: {spec.wg_port}. Remote path: {spec.remote_path}", flush=True)

    if dry_run:
        print(
            "[dry-run] exit-core: upload bundle, compose down (exit-core only)"
            + (" + wipe cascade volume" if wipe_cascade else "")
            + ", nft cleanup, UDP preflight, compose up"
        )
        return

    client = connect_ssh(spec.ssh)
    try:
        code, out, err = run_remote(
            client,
            "docker compose version 2>/dev/null || docker compose version",
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_DOCKER_CHECK,
        )
        if out:
            _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)
        if code != 0:
            raise SystemExit("exit-core: docker compose unavailable")

        tarball = pack_exit_core()
        tmp_tar = "/tmp/amnezia-exit-core.tgz"
        sftp = client.open_sftp()
        try:
            with sftp.open(tmp_tar, "wb") as f:
                f.write(tarball)
        finally:
            sftp.close()

        r = shlex.quote(spec.remote_path)
        tq = shlex.quote(tmp_tar)
        code, out, err = run_remote(
            client,
            f"""set -e
mkdir -p {r}
tar -xzf {tq} -C {r}
rm -f {tq}
""",
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_GIT,
        )
        if out:
            _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)
        if code != 0:
            raise SystemExit("exit-core: extract bundle failed")

        code, out, err = run_remote(
            client,
            build_compose_down_exit_core_script(spec.remote_path, wipe_cascade=wipe_cascade),
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_COMPOSE_DOWN,
        )
        if out:
            _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)

        cleanup_script = build_exit_cleanup_script()
        code, out, err = run_remote(client, cleanup_script, dry_run=False, timeout_sec=REMOTE_TIMEOUT_HOOKS)
        if out:
            _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)

        if not skip_port_check:
            code, out, err = run_remote(
                client,
                build_udp_port_preflight_script(spec.wg_port),
                dry_run=False,
                timeout_sec=REMOTE_TIMEOUT_PREFLIGHT,
            )
            if out:
                _safe_write(sys.stdout, out)
            if err:
                _safe_write(sys.stderr, err)
            if code != 0:
                raise SystemExit("exit-core: UDP port preflight failed")

        wd = shlex.quote(spec.remote_path)
        code, out, err = run_remote(
            client,
            f"cd {wd} && docker compose -f docker-compose.yml pull && docker compose -f docker-compose.yml up -d",
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_DEPLOY,
        )
        if out:
            _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)
        if code == 124:
            raise SystemExit("exit-core: compose up timeout")
        if code != 0:
            raise SystemExit(f"exit-core: compose up failed (exit {code})")
    finally:
        client.close()


def deploy_one(
    spec: HostSpec,
    *,
    dry_run: bool,
    skip_port_check: bool,
    wipe_db: bool,
    wipe_cascade: bool,
    role: str,
) -> None:
    if spec.is_exit_core:
        return deploy_exit_core_stack(
            spec, dry_run=dry_run, skip_port_check=skip_port_check, wipe_cascade=wipe_cascade
        )

    print(f"\n=== Deploy {spec.name.upper()} ({spec.ssh['host']}) ===", flush=True)
    print(
        f"Target ports: UDP {spec.wg_port}, TCP {spec.http_port}/{spec.https_port}. "
        f"Remote path: {spec.remote_path}",
        flush=True,
    )
    print(mask_env_for_print(spec.env_body), flush=True)

    if dry_run:
        print(f"[dry-run] {spec.name}: docker compose version")
        print(f"[dry-run] {spec.name}: sync source")
        print(f"[dry-run] {spec.name}: compose down (own project){' + wipe DB volume' if wipe_db else ''}")
        if wipe_cascade and role == "entry":
            print(f"[dry-run] {spec.name}: (cascade files wiped later in sync step if cascade_enabled)")
        print(f"[dry-run] {spec.name}: cleanup old cascade routing/firewall state ({role})")
        if not skip_port_check:
            print(f"[dry-run] {spec.name}: port preflight")
        print(f"[dry-run] {spec.name}: upload .env")
        print(f"[dry-run] {spec.name}: run deploy.sh")
        print(f"[dry-run] {spec.name}: applyAdminPasswordFromEnv.js")
        return

    client = connect_ssh(spec.ssh)
    try:
        code, out, err = run_remote(
            client,
            "docker compose version 2>/dev/null || docker compose version",
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_DOCKER_CHECK,
        )
        if out:
            _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)
        if code == 124:
            raise SystemExit(f"{spec.name}: docker compose version timeout")
        if code != 0:
            raise SystemExit(f"{spec.name}: docker compose unavailable")

        sync_source(client, spec, dry_run=False)

        code, out, err = run_remote(
            client,
            build_compose_down_script(spec.remote_path, wipe_db=wipe_db),
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_COMPOSE_DOWN,
        )
        if out:
            _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)
        if code == 124:
            raise SystemExit(f"{spec.name}: compose down timeout")
        if code != 0:
            raise SystemExit(f"{spec.name}: compose down failed (exit {code})")

        cleanup_script = build_entry_cleanup_script(spec) if role == "entry" else build_exit_cleanup_script()
        code, out, err = run_remote(client, cleanup_script, dry_run=False, timeout_sec=REMOTE_TIMEOUT_HOOKS)
        if out:
            _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)
        if code == 124:
            raise SystemExit(f"{spec.name}: cascade cleanup timeout")
        if code != 0:
            raise SystemExit(f"{spec.name}: cascade cleanup failed (exit {code})")

        if not skip_port_check:
            code, out, err = run_remote(
                client,
                build_port_preflight_script(spec.remote_path, spec.wg_port, spec.http_port, spec.https_port),
                dry_run=False,
                timeout_sec=REMOTE_TIMEOUT_PREFLIGHT,
            )
            if out:
                _safe_write(sys.stdout, out)
            if err:
                _safe_write(sys.stderr, err)
            if code == 124:
                raise SystemExit(f"{spec.name}: port preflight timeout")
            if code != 0:
                raise SystemExit(
                    f"{spec.name}: port preflight failed (exit {code}); free conflicting ports manually and rerun."
                )
        else:
            print(f"[{spec.name}] skip port preflight")

        sftp = client.open_sftp()
        try:
            with sftp.open(f"{spec.remote_path}/.env", "w") as f:
                f.write(spec.env_body.encode("utf-8"))
        finally:
            sftp.close()

        wd = shlex.quote(spec.remote_path)
        dp = shlex.quote(f"{spec.remote_path}/deploy.sh")
        code, out, err = run_remote(
            client,
            f"chmod +x {dp} && cd {wd} && ./deploy.sh",
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_DEPLOY,
        )
        if out:
            _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)
        if code == 124:
            raise SystemExit(f"{spec.name}: deploy.sh timeout")
        if code != 0:
            raise SystemExit(f"{spec.name}: deploy.sh failed (exit {code})")

        code, out, err = run_remote(
            client,
            f"cd {wd} && docker compose -f docker-compose.yml exec -T amnezia-wg-easy "
            "node scripts/applyAdminPasswordFromEnv.js",
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_ADMIN_SCRIPT,
        )
        if out:
            _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)
        if code == 124:
            raise SystemExit(f"{spec.name}: applyAdminPasswordFromEnv timeout")
        if code != 0:
            raise SystemExit(f"{spec.name}: applyAdminPasswordFromEnv failed (exit {code})")
    finally:
        client.close()


def _cidr_list(values: Any, *, required: bool, ctx: str) -> list[str]:
    if values is None:
        if required:
            raise SystemExit(f"{ctx}: required non-empty list of CIDRs")
        return []
    if not isinstance(values, list) or not values:
        if required:
            raise SystemExit(f"{ctx}: required non-empty list of CIDRs")
        return []
    out = [str(x).strip() for x in values if str(x).strip()]
    if required and not out:
        raise SystemExit(f"{ctx}: empty CIDR list")
    return out


def _str_cfg(d: dict[str, Any], key: str, default: str = "") -> str:
    v = d.get(key)
    if v is None:
        return default
    return str(v).strip()


def _parse_tunnel_settings(entry: HostSpec, exit_spec: HostSpec) -> dict[str, Any]:
    ecfg = entry.network
    xcfg = exit_spec.network
    entry_ip = _str_cfg(ecfg, "cascade_entry_ip", _str_cfg(xcfg, "cascade_entry_ip", "172.31.255.1"))
    exit_ip = _str_cfg(ecfg, "cascade_exit_ip", _str_cfg(xcfg, "cascade_exit_ip", "172.31.255.2"))
    prefix = _str_cfg(ecfg, "cascade_prefix_len", _str_cfg(xcfg, "cascade_prefix_len", "30"))
    listen_port = _str_cfg(
        xcfg, "cascade_listen_port", _str_cfg(ecfg, "cascade_listen_port", str(CASCADE_DEFAULT_LISTEN_PORT))
    )
    return {
        "entry_ip": entry_ip,
        "exit_ip": exit_ip,
        "prefix": prefix,
        "listen_port": listen_port,
    }


def _cascade_tunnel_network_cidr(entry: HostSpec, exit_spec: HostSpec) -> str | None:
    p = _parse_tunnel_settings(entry, exit_spec)
    try:
        iface = ipaddress.ip_interface(f"{p['entry_ip']}/{p['prefix']}")
        return str(iface.network)
    except ValueError:
        return None


def _parse_awg0_interface_fields(awg0_conf: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    in_iface = False
    for line in awg0_conf.splitlines():
        s = line.strip()
        if s == "[Interface]":
            in_iface = True
            continue
        if s.startswith("[") and s != "[Interface]":
            in_iface = False
            continue
        if in_iface and "=" in s:
            k, _, v = s.partition("=")
            key = k.strip()
            if key in ("PrivateKey", "Address", "ListenPort", "PreUp", "PostUp", "PreDown", "PostDown"):
                continue
            fields[key] = v.strip()
    for req in ("Jc", "Jmin", "Jmax", "S1", "S2", "S3", "S4", "H1", "H2", "H3", "H4"):
        if req not in fields:
            raise SystemExit(f"awg0.conf [Interface] missing {req} (need full server block for cascade)")
    return fields


def _build_exit_cascade_conf_text(
    iface_fields: dict[str, str],
    exit_private_key: str,
    entry_cascade_public_key: str,
    exit_address_cidr: str,
    listen_port: int,
    allowed_ips: str,
) -> str:
    lines = [
        "# Generated by remote-deploy-cascade/install.py",
        "",
        "[Interface]",
        f"PrivateKey = {exit_private_key.strip()}",
        f"Address = {exit_address_cidr}",
        f"ListenPort = {int(listen_port)}",
    ]
    for k in ("Jc", "Jmin", "Jmax", "S1", "S2", "S3", "S4", "H1", "H2", "H3", "H4"):
        lines.append(f"{k} = {iface_fields[k]}")
    lines.extend(
        [
            "",
            "[Peer]",
            f"PublicKey = {entry_cascade_public_key.strip()}",
            f"AllowedIPs = {allowed_ips}",
            "",
        ]
    )
    return "\n".join(lines)


def tunnel_params_for_exit_hooks(exit_spec: HostSpec, entry: HostSpec | None = None) -> dict[str, Any]:
    wan = str(exit_spec.network.get("wan_interface") or "").strip()
    if not wan:
        raise SystemExit("exit.network.wan_interface is required")
    tunnel_cidr = ""
    if entry is not None:
        tunnel_cidr = _cascade_tunnel_network_cidr(entry, exit_spec) or ""
    return {
        "iface": "exit-cascade",
        "wan_if": wan,
        "client_cidrs": _cidr_list(exit_spec.network.get("client_cidrs"), required=True, ctx="exit.network.client_cidrs"),
        "tunnel_cidr": tunnel_cidr,
    }


def build_exit_hook_script(tunnel: dict[str, Any]) -> str:
    uplink_if = str(tunnel["iface"]).strip()
    wan_if = str(tunnel["wan_if"]).strip()
    client_cidrs = tunnel["client_cidrs"]
    cidrs = " ".join(shlex.quote(c) for c in client_cidrs)
    uplink_q = shlex.quote(uplink_if)
    wan_q = shlex.quote(wan_if)
    tun = str(tunnel.get("tunnel_cidr") or "").strip()
    tun_q = shlex.quote(tun) if tun else ""
    tunnel_fwd = ""
    if tun:
        tunnel_fwd = (
            f'nft add rule inet amnezia_cascade_exit_fwd forward iifname "$WAN_IF" '
            f'oifname "$UPLINK_IF" ip daddr {tun_q} accept\n'
        )
    daddr_clients = ""
    for c in client_cidrs:
        daddr_clients += (
            f'nft add rule inet amnezia_cascade_exit_fwd forward iifname "$WAN_IF" '
            f'oifname "$UPLINK_IF" ip daddr {shlex.quote(c)} accept\n'
        )
    snat_tunnel = ""
    if tun:
        snat_tunnel = f"  nft add rule ip amnezia_cascade_exit_nat postrouting oifname \"$WAN_IF\" ip saddr {tun_q} masquerade 2>/dev/null || true\n"
    return f"""set -e
UPLINK_IF={uplink_q}
WAN_IF={wan_q}
CLIENT_CIDRS="{cidrs}"

sysctl -w net.ipv4.ip_forward=1 >/dev/null
sysctl -w net.ipv4.conf.all.rp_filter=0 >/dev/null 2>&1 || true

nft add table ip amnezia_cascade_exit_nat 2>/dev/null || true
nft 'add chain ip amnezia_cascade_exit_nat postrouting {{ type nat hook postrouting priority 100; policy accept; }}' 2>/dev/null || true
nft flush chain ip amnezia_cascade_exit_nat postrouting
for c in $CLIENT_CIDRS; do
  nft add rule ip amnezia_cascade_exit_nat postrouting oifname "$WAN_IF" ip saddr "$c" masquerade
done
{snat_tunnel}
nft add table inet amnezia_cascade_exit_fwd 2>/dev/null || true
nft 'add chain inet amnezia_cascade_exit_fwd forward {{ type filter hook forward priority 1; policy accept; }}' 2>/dev/null || true
nft flush chain inet amnezia_cascade_exit_fwd forward
nft add rule inet amnezia_cascade_exit_fwd forward iifname "$UPLINK_IF" oifname "$WAN_IF" accept
{tunnel_fwd}{daddr_clients}nft add rule inet amnezia_cascade_exit_fwd forward iifname "$WAN_IF" oifname "$UPLINK_IF" ct state established,related accept

echo "exit cascade hook applied (uplink=$UPLINK_IF wan=$WAN_IF)."
"""


def sync_cascade_configs(
    entry: HostSpec,
    exit_spec: HostSpec,
    *,
    dry_run: bool,
    wipe_cascade: bool,
) -> None:
    """Align exit-cascade.conf on S2 with awg0 Amnezia params on S1; publish peer keys."""
    print("\n=== Sync cascade AmneziaWG configs ===", flush=True)
    if dry_run:
        print("[dry-run] would sync exit-cascade.conf and peer files")
        return
    if not _truthy(entry.network.get("cascade_enabled")):
        print("[sync] cascade_enabled false on entry — skip")
        return
    if not exit_spec.is_exit_core:
        raise SystemExit("sync_cascade_configs requires exit.core: true (exit-core stack)")

    p = _parse_tunnel_settings(entry, exit_spec)
    try:
        listen = int(str(p["listen_port"]))
    except ValueError as e:
        raise SystemExit("cascade_listen_port must be integer") from e
    entry_host = str(exit_spec.ssh.get("host", "")).strip()
    endpoint_line = f"{entry_host}:{listen}" if entry_host else ""

    client_cidrs = _cidr_list(entry.network.get("client_cidrs"), required=True, ctx="entry.network.client_cidrs")
    allowed_ips = ",".join([f"{p['entry_ip']}/32"] + client_cidrs)
    exit_addr = f"{p['exit_ip']}/{p['prefix']}"

    en = connect_ssh(entry.ssh)
    try:
        if wipe_cascade:
            wipe_e = """docker exec amnezia-awg rm -f \
/opt/amnezia/awg/cascade_link.private /opt/amnezia/awg/cascade_link.public \
/opt/amnezia/awg/cascade_exit.public /opt/amnezia/awg/cascade_exit.endpoint \
/opt/amnezia/awg/awg-cascade.conf 2>/dev/null || true"""
            run_remote(en, wipe_e, dry_run=False, timeout_sec=REMOTE_TIMEOUT_HOOKS)
        wd = shlex.quote(entry.remote_path)
        node_save0 = (
            "require('./lib/WireGuard').saveConfig().then(()=>process.exit(0))"
            ".catch(e=>{console.error(e);process.exit(1);})"
        )
        trig = f"""set -e
cd {wd}
docker compose exec -T amnezia-wg-easy node -e {shlex.quote(node_save0)}
"""
        code, out, err = run_remote(en, trig, dry_run=False, timeout_sec=REMOTE_TIMEOUT_SYNC)
        if out:
            _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)
        if code != 0:
            raise SystemExit(f"entry: trigger WireGuard.saveConfig failed (exit {code})")

        code, out, err = run_remote(
            en,
            "docker exec amnezia-awg cat /opt/amnezia/awg/awg0.conf",
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_SYNC,
        )
        if code != 0:
            raise SystemExit("entry: cannot read awg0.conf from container")
        iface_fields = _parse_awg0_interface_fields(out)

        code, out, err = run_remote(
            en,
            "docker exec amnezia-awg cat /opt/amnezia/awg/cascade_link.public",
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_SYNC,
        )
        if code != 0 or not out.strip():
            raise SystemExit("entry: cascade_link.public missing — ensure WG_CASCADE_ENABLED on entry")
        entry_cascade_pub = out.strip()
    finally:
        en.close()

    ex = connect_ssh(exit_spec.ssh)
    try:
        if wipe_cascade:
            wipe_x = """docker exec amnezia-exit-cascade rm -f \
/config/exit_link.private /config/exit_link.public /config/exit-cascade.conf 2>/dev/null || true"""
            run_remote(ex, wipe_x, dry_run=False, timeout_sec=REMOTE_TIMEOUT_HOOKS)

        key_init = """set -e
docker exec amnezia-exit-cascade sh -c 'test -s /config/exit_link.private || wg genkey > /config/exit_link.private'
docker exec amnezia-exit-cascade sh -c 'wg pubkey < /config/exit_link.private > /config/exit_link.public'
"""
        code, out, err = run_remote(ex, key_init, dry_run=False, timeout_sec=REMOTE_TIMEOUT_SYNC)
        if out:
            _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)
        if code != 0:
            raise SystemExit("exit-core: key init failed")

        code, priv, err = run_remote(
            ex,
            "docker exec amnezia-exit-cascade cat /config/exit_link.private",
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_SYNC,
        )
        if code != 0:
            raise SystemExit("exit-core: read exit_link.private failed")
        code, pub_out, err = run_remote(
            ex,
            "docker exec amnezia-exit-cascade cat /config/exit_link.public",
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_SYNC,
        )
        if code != 0:
            raise SystemExit("exit-core: read exit_link.public failed")
        exit_pub = pub_out.strip()

        conf_text = _build_exit_cascade_conf_text(
            iface_fields,
            priv.strip(),
            entry_cascade_pub,
            exit_addr,
            listen,
            allowed_ips,
        )
        sftp_x = ex.open_sftp()
        try:
            with sftp_x.open("/tmp/exit-cascade-gen.conf", "wb") as rf:
                rf.write(conf_text.encode("utf-8"))
        finally:
            sftp_x.close()
        code, out, err = run_remote(
            ex,
            "docker cp /tmp/exit-cascade-gen.conf amnezia-exit-cascade:/config/exit-cascade.conf && rm -f /tmp/exit-cascade-gen.conf",
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_SYNC,
        )
        if code != 0:
            raise SystemExit("exit-core: install exit-cascade.conf failed")
    finally:
        ex.close()

    en = connect_ssh(entry.ssh)
    try:
        pub_wr = (
            f"printf '%s\\n' {shlex.quote(exit_pub)} | "
            "docker exec -i amnezia-awg sh -c 'cat > /opt/amnezia/awg/cascade_exit.public'"
        )
        code, out, err = run_remote(en, pub_wr, dry_run=False, timeout_sec=REMOTE_TIMEOUT_SYNC)
        if code != 0:
            raise SystemExit("entry: write cascade_exit.public failed")
        if endpoint_line:
            ep_wr = (
                f"printf '%s\\n' {shlex.quote(endpoint_line)} | "
                "docker exec -i amnezia-awg sh -c 'cat > /opt/amnezia/awg/cascade_exit.endpoint'"
            )
            run_remote(en, ep_wr, dry_run=False, timeout_sec=REMOTE_TIMEOUT_SYNC)
        wd = shlex.quote(entry.remote_path)
        node_save = (
            "require('./lib/WireGuard').saveConfig().then(()=>process.exit(0))"
            ".catch(e=>{console.error(e);process.exit(1);})"
        )
        code, out, err = run_remote(
            en,
            f"cd {wd} && docker compose exec -T amnezia-wg-easy node -e {shlex.quote(node_save)}",
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_SYNC,
        )
        if code != 0:
            raise SystemExit("entry: second saveConfig after peer files failed")
        code, out, err = run_remote(
            en,
            f"cd {wd} && docker compose restart amnezia-wg-easy",
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_DEPLOY,
        )
        if out:
            _safe_write(sys.stdout, out)
    finally:
        en.close()

    ex = connect_ssh(exit_spec.ssh)
    try:
        code, out, err = run_remote(
            ex,
            "docker restart amnezia-exit-cascade",
            dry_run=False,
            timeout_sec=REMOTE_TIMEOUT_DEPLOY,
        )
        if out:
            _safe_write(sys.stdout, out)
        if code != 0:
            raise SystemExit("exit-core: restart failed")
    finally:
        ex.close()

    print("[sync] cascade configs and restarts done.", flush=True)


def build_entry_cleanup_script(entry: HostSpec) -> str:
    local_cidrs = _cidr_list(entry.network.get("local_cidrs"), required=False, ctx="entry.network.local_cidrs")
    local_join = " ".join(shlex.quote(c) for c in local_cidrs)
    client_cidrs = _cidr_list(entry.network.get("client_cidrs"), required=False, ctx="entry.network.client_cidrs")
    client_join = " ".join(shlex.quote(c) for c in client_cidrs)
    return f"""set -e
LOCAL_CIDRS="{local_join}"
CLIENT_CIDRS="{client_join}"
while ip rule show | grep -q "fwmark 0x66 .* lookup 166"; do
  p=$(ip rule show | awk '/fwmark 0x66 .* lookup 166/ {{gsub(":","",$1); print $1; exit}}')
  [ -n "$p" ] && ip rule del pref "$p" 2>/dev/null || break
done
if [ -n "$CLIENT_CIDRS" ]; then
  for c in $CLIENT_CIDRS; do
    while ip rule show | grep -q "from $c lookup 166"; do
      p=$(ip rule show | awk -v c="$c" '$0 ~ ("from " c " lookup 166") {{gsub(":","",$1); print $1; exit}}')
      [ -n "$p" ] && ip rule del pref "$p" 2>/dev/null || break
    done
  done
fi
ip route flush table 166 2>/dev/null || true
if [ -n "$LOCAL_CIDRS" ]; then
  for c in $LOCAL_CIDRS; do
    while ip rule show | grep -q "to $c lookup main"; do
      p=$(ip rule show | awk -v cidr="$c" '$0 ~ ("to " cidr " lookup main") {{gsub(":","",$1); print $1; exit}}')
      [ -n "$p" ] && ip rule del pref "$p" 2>/dev/null || break
    done
  done
fi
nft delete table inet amnezia_cascade_entry 2>/dev/null || true
echo "entry cascade state cleaned."
"""


def build_exit_cleanup_script() -> str:
    return """set -e
nft delete table ip amnezia_cascade_exit_nat 2>/dev/null || true
nft delete table inet amnezia_cascade_exit_fwd 2>/dev/null || true
echo "exit cascade state cleaned."
"""


def apply_cascade_hooks(
    exit_spec: HostSpec, *, entry: HostSpec | None = None, dry_run: bool
) -> None:
    """Host nft NAT/forward on exit only (interface exit-cascade, network_mode host)."""
    print("\n=== Apply exit cascade hooks (host) ===", flush=True)
    tunnel = tunnel_params_for_exit_hooks(exit_spec, entry=entry)
    exit_script = build_exit_hook_script(tunnel)
    if dry_run:
        print("[dry-run] would apply exit host nft hooks")
        return

    ex_client = connect_ssh(exit_spec.ssh)
    try:
        code, out, err = run_remote(ex_client, exit_script, dry_run=False, timeout_sec=REMOTE_TIMEOUT_HOOKS)
        if out:
            _safe_write(sys.stdout, out)
        if err:
            _safe_write(sys.stderr, err)
        if code == 124:
            raise SystemExit("exit hook timeout")
        if code != 0:
            raise SystemExit(f"exit hook failed (exit {code})")
    finally:
        ex_client.close()


def resolve_config_path(explicit: Path | None) -> Path:
    if explicit is not None:
        return explicit
    for name in ("config.yaml", "deploy-runtime.yaml"):
        p = WORK_DIR / name
        if p.is_file():
            return p
    return WORK_DIR / "config.yaml"


def main() -> None:
    ap = argparse.ArgumentParser(description="Deploy entry+exit cascade over SSH from YAML config.")
    ap.add_argument(
        "-c",
        "--config",
        type=Path,
        default=None,
        help=f"Config path (default first of {WORK_DIR / 'config.yaml'} or {WORK_DIR / 'deploy-runtime.yaml'})",
    )
    ap.add_argument("--dry-run", action="store_true", help="Print actions; no SSH mutations.")
    ap.add_argument("--skip-port-check", action="store_true", help="Skip remote port preflight checks.")
    ap.add_argument(
        "--wipe-db",
        action="store_true",
        help=(
            "Also wipe panel DB volume (amnezia-wg-data) during reinstall. "
            "Default: preserve DB."
        ),
    )
    ap.add_argument(
        "--wipe-cascade",
        action="store_true",
        help=(
            "Remove cascade keys/volumes: exit Docker volume for exit-cascade; "
            "cascade files in the panel WG volume on entry. Default: preserve between reinstalls."
        ),
    )
    ap.add_argument(
        "--phase",
        choices=("exit-only", "entry-only", "full"),
        default="full",
        help="Run only one side or full cascade (default).",
    )
    args = ap.parse_args()

    config_path = resolve_config_path(args.config)
    if not config_path.is_file():
        sys.exit(f"Config not found: {config_path}")
    if not ENV_EXAMPLE.is_file():
        sys.exit(f".env.example not found at {ENV_EXAMPLE}")

    raw = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    try:
        cfg = expand_env_vars(raw)
    except KeyError as e:
        sys.exit(f"Config env error: {e}")

    order, defaults = parse_env_example(ENV_EXAMPLE)
    common_source = cfg.get("source") if isinstance(cfg.get("source"), dict) else {}

    entry = parse_host_spec("entry", cfg, common_source, order, defaults)
    exit_spec = parse_host_spec("exit", cfg, common_source, order, defaults)

    print(f"Using config: {config_path}")
    print(f"Phase: {args.phase}")
    print(f"Wipe DB: {'yes' if args.wipe_db else 'no (default preserve)'}")
    print(f"Wipe cascade: {'yes' if args.wipe_cascade else 'no (default preserve)'}")

    cascade_on = _truthy(entry.network.get("cascade_enabled"))
    if cascade_on and not exit_spec.is_exit_core:
        sys.exit(
            "entry.network.cascade_enabled requires exit.core: true (or exit.mode: core). "
            "See remote-deploy-cascade/config.example.yaml."
        )

    if args.phase in ("exit-only", "full"):
        deploy_one(
            exit_spec,
            dry_run=args.dry_run,
            skip_port_check=args.skip_port_check,
            wipe_db=args.wipe_db,
            wipe_cascade=args.wipe_cascade,
            role="exit",
        )
    if args.phase in ("entry-only", "full"):
        deploy_one(
            entry,
            dry_run=args.dry_run,
            skip_port_check=args.skip_port_check,
            wipe_db=args.wipe_db,
            wipe_cascade=args.wipe_cascade,
            role="entry",
        )

    if cascade_on and exit_spec.is_exit_core:
        if args.phase in ("full", "entry-only"):
            sync_cascade_configs(
                entry,
                exit_spec,
                dry_run=args.dry_run,
                wipe_cascade=args.wipe_cascade,
            )
        if args.phase in ("full", "entry-only", "exit-only"):
            apply_cascade_hooks(
                exit_spec,
                entry=entry if cascade_on else None,
                dry_run=args.dry_run,
            )

    if args.dry_run:
        print("\n[dry-run] done.")
    else:
        print("\nDone.")
        entry_url = entry.merged_env.get("PANEL_DOMAIN", entry.merged_env.get("WG_HOST", "?"))
        print(f"  Entry panel: https://{entry_url}")
        if exit_spec.is_exit_core:
            print(
                f"  Exit core:   {exit_spec.ssh.get('host', '?')} "
                f"(AmneziaWG exit-cascade, path {exit_spec.remote_path})"
            )
        else:
            print(
                f"  Exit panel:  https://{exit_spec.merged_env.get('PANEL_DOMAIN', exit_spec.merged_env.get('WG_HOST', '?'))}"
            )
        if cascade_on and exit_spec.is_exit_core:
            print("  Verify: README — awg show awg-cascade (entry container), awg show exit-cascade (exit), nft on exit host.")


if __name__ == "__main__":
    main()
